export const Images = {
  SIGNUPBACKGROUND: require("./resources/signUpBg.png"),
  BLUR: require("./resources/noise.png"),
  HLINE: require("./resources/horizontalLine.png"),
  MARKGROUP: require("./resources/Mask group.png"),
  ADD: require("./resources/add.png"),
  SUB: require("./resources/minus.png"),
  ACCORDIAN_GARROW: require("./resources/accordianArrow.png"),
  ACCORDIAN_ARROW: require("./resources/accordianNormalArrow.png"),
  SOCIAL: require("./resources/social.png"),
  TWITTER: require("./resources/twitter.png"),
  INSTA: require("./resources/insta.png"),
  TELIGRAM: require("./resources/teligram.png"),
  DISCORD: require("./resources/discord.png"),
  RADDIT: require("./resources/raddit.png"),
  LINKEDIN: require("./resources/linkedin.png"),
  FACEBOOK: require("./resources/facebook.png"),
  COMBAT_BG: require("./resources/combatBg.png"),
  DIPLOMACY_BG: require("./resources/diplomacyBg.png"),
  CRAFTING_BG:  require("./resources/craftingBg.png"),
  EXPLORATION_BG: require("./resources/explorationBg.png"),
  COMBAT: require("./resources/Combat.png"),
  DIPLOMACY: require("./resources/Diplomacy.png"),
  CRAFTING:  require("./resources/Crafting.png"),
  EXPLORATION: require("./resources/Exploration.png"),
};
